### ISSUE TITLE
DailyRewards V 1.3.2

### ISSUE THREAD

**Issue by Wazupbutrcup** [Revivalo/DailyRewards#2]
Disabled the command /reward by giving my players the permission node: "lp group default permission set dailyreawrd.use false"

But they can still use /rewards to claim the dailys/weeklys/monthlys

**Comment by Revivalo** [comment]
dailyreawrd.use permission allow only the /rewards command.
For the rewards itself you must set false this permission(s): dailyreward.<typeOfReward>
