### ISSUE TITLE
PERMISSION DAILYREWARD.USE NOT WORKING

### ISSUE THREAD

**Issue by HonzasikCZ** [Revivalo/DailyRewards#6]
Hello,

In the last update of the plugin, I found out that allowing players to open the menu (dailyreward.use) doesn't work, and /dailyreward claim doesn't work either

Everything is fine when I have permission *

I will be very happy for the answer :)

Thanks for reading <3

**Comment by Revivalo** [comment]
Hello! Fixed in latest version. You can found it here: https://www.spigotmc.org/resources/%E2%9A%A1-daily-weekly-monthly-rewards-mysql-oraxen-itemsadder-support-1-8-8-1-19-3.81780/
